apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_ID: MjE1NTEyNjU2MTMyLW5yZDk0aGRkbGxnbHZ2bmw4a2RvYjFzODVsdDQwYmh0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_SECRET: R09DU1BYLUEyeTVkOEluazhwVWVVdUFBS3dYT3NwNFJhNDc=
  NEXTAUTH_SECRET: bDlrbHhvMmc1enF5R29lN202S0krVmFrMFRyNVBtbFM5Rm5GemVSVnlzZz0=
  NEXT_PUBLIC_API_KEY: QUl6YVN5RFVzS3ZBVHVTM1ZGU1FJemdpYlE2QW44bmFxbWoxY0N3
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9zdXJ5YW5zaGdqaWl0OlFiTU9WNGRsSkxXbVhNZlFAZ2VtaW5pLjFjM3pnZ2wubW9uZ29kYi5uZXQvP2FwcE5hbWU9Z2VtaW5p
